### ISSUE TITLE
Develop Messaging Routes and Schema

### ISSUE THREAD

**Issue by Suuugi** [jonathanpchan/openclassroom#126]
Develop messaging routes and schema. It should be broken down as:

{
    _id,
    uname1,
    uname2,
    messages: {
        sender,
        timestamp,
        message
    }
}

routes should be
/add which takes sender and message
/getmessagelist should take a value of 0 or 1 (for initial load)

**Comment by jtnguyen95** [comment]
Created the routes/schema/functions to retrieve data for messaging
getMessages();
saveMessage();
CreateNewChat();
