### ISSUE TITLE
Update Past Issues with Descriptions

### ISSUE THREAD

**Issue by Suuugi** [jonathanpchan/openclassroom#143]
Update the Waffle issues with descriptions and comments about the issues that were covered for backtracking.

**Comment by Suuugi** [comment]
https://github.com/jonathanpchan/openclassroom/issues

**Comment by jtnguyen95** [comment]
Updated my waffles w/ a description of what I did

**Comment by Suuugi** [comment]
Went through all closed items and added comments about what was accomplished through each issue.

**Comment by jonathanpchan** [comment]
I updated my issues with descriptions
