### ISSUE TITLE
Understand MEAN Stack back to front structure

### ISSUE THREAD

**Issue by jonathanpchan** [jonathanpchan/openclassroom#15]
Alter back end structure to reflect the new understanding of the mean stack.

**Comment by Suuugi** [comment]
Figured out how it works in week 3 and acted on it.

**Comment by Suuugi** [comment]
Routes are the link extensions tied to the models.
Models are the structure of the database collections.
Services are where the post and get request are made.
Typescript/HTML/CSS is what uses the services to get the data and display on the front end.
