### ISSUE TITLE
Develop User Schedule Schema

### ISSUE THREAD

**Issue by Suuugi** [jonathanpchan/openclassroom#33]
Create User Schedule Schema for front end to work with. This includes data.

**Comment by jtnguyen95** [comment]
main takeaway: 
// Classes Schema
const classesSchema = mongoose.Schema({
    name: { type: String },
    num : { type: String },
    sec : { type: String },
    day :  { type: String },
    time : { type: String },
    location : { type: String },
    prof : { type: String }
})

// User Schema
const UserSchema = mongoose.Schema({
  name: { type: String },
  lName: { type: String},
  email: { type: String, required: true },
  username: { type: String, required: true },
  password: { type: String, required: true },
  regdate: { type: Date, required: true },
  emailVerified: {type: Boolean, required: false},
  schedule: { type: [classesSchema] }
});
