### ISSUE TITLE
Develop Room Info Schema

### ISSUE THREAD

**Issue by Suuugi** [jonathanpchan/openclassroom#40]
Develop the schema for the Room info. So what does this entail? How much information in each room?

**Comment by jtnguyen95** [comment]
Main takeaway:
// Class Section Schema
const ClassSectionSchema = mongoose.Schema({
  name : {type: String},
  sec :  {type: String},
  days :  {type: String},
  location :  {type: String},
  st :  {type: Number},
  et :  {type: Number}
});

// Room Schema (Mon -> Thurs)
const RoomSchema = mongoose.Schema({
  name : {type: String},
  mon : {type: [ClassSectionSchema]},
  tue : {type: [ClassSectionSchema]},
  wed : {type: [ClassSectionSchema]},
  thu : {type: [ClassSectionSchema]},
  //open times
  omon : {type: [ClassSectionSchema]},
  otue : {type: [ClassSectionSchema]},
  owed : {type: [ClassSectionSchema]},
  othu : {type: [ClassSectionSchema]}
});
