### ISSUE TITLE
Apply CSS to Find Classroom for Responsiveness

### ISSUE THREAD

**Issue by whathappenedman** [jonathanpchan/openclassroom#59]
Make the color scheme more CSULB-like.
Make the buttons more visible.
Make sure the display scales down to the phone.

**Comment by Suuugi** [comment]
This will be touched up on refactor week.

**Comment by Suuugi** [comment]
Updated the colors to be #edaa00 and #333333, #222222, and #111111 and others to follow the same formatted color of the CSULB website. Also make use of @media queries to scale the phone down.
