### ISSUE TITLE
Delete Course from User Function

### ISSUE THREAD

**Issue by Suuugi** [jonathanpchan/openclassroom#78]
Add delete courses functionality if a user wants to delete a course.

**Comment by Suuugi** [comment]
Waiting on the delete query to continue onward.

**Comment by jtnguyen95** [comment]
Created the delete query/route for Nick

module.exports.deleteScheduleItem = function(eMail, crsID, callback) {
    User.findOneAndUpdate(
        {"email": eMail}, {
            $pull : {
                "schedule" : { sec : crsID }
            }
        }, {new: true}, function(err) {
            if (err) {
                console.log("Something went wrong when deleting a class!");
            }
            User.find({email: eMail}, {schedule: 1, _id:0}, callback);
        })
};

**Comment by Suuugi** [comment]
Created a trash button to remove a course and added a confirmation page to reduce human error in an accidental remove.
