### ISSUE TITLE
Delete Schedule Item Query

### ISSUE THREAD

**Issue by whathappenedman** [jonathanpchan/openclassroom#81]
Create query that takes email and section number and removes from user schedule.

**Comment by jtnguyen95** [comment]
module.exports.deleteScheduleItem = function(eMail, crsID, callback) {
User.findOneAndUpdate(
{"email": eMail}, {
$pull : {
"schedule" : { sec : crsID }
}
}, {new: true}, function(err) {
if (err) {
console.log("Something went wrong when deleting a class!");
}
User.find({email: eMail}, {schedule: 1, _id:0}, callback);
})
};
